steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/cis-frontend:production",
        "-f",
        "Dockerfile.frontend",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/cis-frontend:production"
timeout: "300s"
