steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cis-frontend:latest'
      - '-f'
      - 'Dockerfile.frontend'
      - '.'

  # Step 2: Push latest tag to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cis-frontend:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cis-frontend'
      - '--image=gcr.io/$PROJECT_ID/cis-frontend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=60'
      - '--max-instances=5'
      - '--min-instances=0'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-secrets=SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_KEY=SUPABASE_KEY:latest,API_BASE_URL=API_BASE_URL:latest,FRONTEND_URL=FRONTEND_URL:latest'

images:
  - 'gcr.io/$PROJECT_ID/cis-frontend:latest'

timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'
