steps:
  # Step 1: Build the container image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-api"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/gnx-cis:latest"
      - "-f"
      - "Dockerfile.api"
      - "."

  # Step 2: Push latest tag to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-latest"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/gnx-cis:latest"

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-run"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "gnx-cis"
      - "--image=gcr.io/$PROJECT_ID/gnx-cis:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--timeout=300"
      - "--max-instances=10"
      - "--min-instances=1"
      - "--cpu-boost"
      - "--port=8080"
      - "--set-env-vars=ENVIRONMENT=production,GCP_PROJECT_ID=$PROJECT_ID"
      - "--set-secrets=SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_KEY=SUPABASE_KEY:latest,SUPABASE_SERVICE_KEY=SUPABASE_SERVICE_KEY:latest,SUPABASE_JWT_SECRET=SUPABASE_JWT_SECRET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,LINKEDIN_CLIENT_ID=LINKEDIN_CLIENT_ID:latest,LINKEDIN_CLIENT_SECRET=LINKEDIN_CLIENT_SECRET:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest,API_BASE_URL=API_BASE_URL:latest,CLERK_SECRET_KEY=CLERK_SECRET_KEY:latest,CLERK_PUBLISHABLE_KEY=CLERK_PUBLISHABLE_KEY:latest"

images:
  - "gcr.io/$PROJECT_ID/gnx-cis:latest"

timeout: "1200s"

options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  substitution_option: "ALLOW_LOOSE"
