steps:
  # Build the API container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cis-api:$COMMIT_SHA', '-f', 'Dockerfile.api', '.']

  # Build the Frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cis-frontend:$COMMIT_SHA', '-f', 'Dockerfile.frontend', '.']

  # Push the API container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cis-api:$COMMIT_SHA']

  # Push the Frontend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cis-frontend:$COMMIT_SHA']

  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cis-api'
      - '--image=gcr.io/$PROJECT_ID/cis-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=CLERK_SECRET_KEY=${_CLERK_SECRET_KEY},CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY},SUPABASE_URL=${_SUPABASE_URL},SUPABASE_KEY=${_SUPABASE_KEY},API_BASE_URL=${_API_BASE_URL},FRONTEND_URL=${_FRONTEND_URL}'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cis-frontend'
      - '--image=gcr.io/$PROJECT_ID/cis-frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=API_BASE_URL=${_API_BASE_URL},CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/cis-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cis-frontend:$COMMIT_SHA'

substitutions:
  _CLERK_SECRET_KEY: ''
  _CLERK_PUBLISHABLE_KEY: ''
  _SUPABASE_URL: ''
  _SUPABASE_KEY: ''
  _API_BASE_URL: 'https://cis-api-xxxxxxxxxx-uc.a.run.app'
  _FRONTEND_URL: 'https://cis-frontend-xxxxxxxxxx-uc.a.run.app'